package Interview.BT.Exception;

public class ActualReturn {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		ActualReturn testReturn = new ActualReturn();
		System.out.println("Value = "+testReturn.testReturn());

	}

	private int testReturn(){
		try{
			System.out.println("Before return");
			return 1;
		}catch (Exception ex){
			System.out.println("inside Exception");
			//return 2;

		}finally{
			System.out.println("inside finally");
			//	return 3;
		}

		System.out.println("After the try block");
		return 4;
	}

}


