package Interview.BT.Exception;

public class TestReturn {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		TestReturn testReturn = new TestReturn();
		testReturn.testReturn();

	}

	private void testReturn(){
		try{
			System.out.println("Before return");
			return;
		}catch (Exception ex){
			System.out.println("inside Exception");

		}finally{
			System.out.println("inside finally");
		}
		System.out.println("After the try block");
	}

}
